### ISSUE TITLE
layout of the page behaves inconsistently across different browsers

### ISSUE THREAD

**Issue by lzh12311** [24-S1-2-C-Moral-Decisions/LandingSite#34]
We have observed that the layout of the page behaves inconsistently across different browsers during front-end development. Specifically, the positions, sizes, and alignments of certain elements differ depending on the browser being used.

The page layout behaves inconsistently across different browsers, with the following specific issues:

- In Chrome, certain elements are misaligned and do not match the design specifications.
- In Firefox, some elements appear larger or smaller than in Chrome, causing layout disruptions.
- In Safari, certain CSS effects (e.g., transitions) are not applied correctly.

**Comment by Xinlong-Wu** [comment]
Move To jira
