### ISSUE TITLE
[Risk]

### ISSUE THREAD

**Issue by Universe-E** [24-S1-2-C-Moral-Decisions/LandingSite#36]
## Description

There might be differences in user experience between mobile and desktop users due to variations in screen sizes, touch interactions, and performance capabilities. This can lead to inconsistent form behavior and layout issues, potentially impacting the survey completion rate and data accuracy.

## Mitigation Strategy

Utilize responsive design techniques with frameworks like Bootstrap and media queries to ensure the survey form adapts seamlessly across different devices. Implement thorough testing on both mobile and desktop platforms to identify and resolve any discrepancies in user experience.

## Follow-up Actions

Conduct regular testing on various devices and screen sizes, particularly when rolling out updates or new features. Gather user feedback to identify and address any remaining issues. Maintain and update documentation to reflect the results of device compatibility tests and solutions applied.

**Comment by Xinlong-Wu** [comment]
Move To Jira
