### ISSUE TITLE
[UI Issue] Different shadow Style of Search Box

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#62]
**Issue On:** Front End

**Describe the bug**
Different Style of Search Box

**Current implementation**
![image](https://github.com/user-attachments/assets/ffedae3a-e3d8-41b5-a315-435366e987d7)

**Expected implementation （On Figma）**
![image](https://github.com/user-attachments/assets/b135500e-7c08-4bea-84f3-32b8dc9f9347)

**Comment by c1c4da3300** [comment]
fixed
<img width="532" alt="image" src="https://github.com/user-attachments/assets/ffa3a963-8161-4772-8b6c-af71d6577e51">

https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/commit/baf316ca55cebe7e909b1a6aa709f47aacd2c6c7
