### ISSUE TITLE
[UI Issue] No Placeholder text in Search Box

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#63]
**Issue On:** Front End

**Describe the bug**
No Placeholder text in Search Box

**Current implementation**
![image](https://github.com/user-attachments/assets/6c683861-db11-40ca-b66b-adaae673c2a0)

**Expected implementation （On Figma）**
![image](https://github.com/user-attachments/assets/3429da99-c602-42d1-b0ce-d5033bacd993)

**Comment by c1c4da3300** [comment]
Fixed
<img width="505" alt="image" src="https://github.com/user-attachments/assets/61588053-bf99-462b-adff-04ddd24c1897">
