### ISSUE TITLE
[UI Issue] There is a Black border when box is focused

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#64]
**Issue On:** Front End 

**Describe the bug**
There is a Black border when box is focused

**Current implementation**
![image](https://github.com/user-attachments/assets/ac2896f1-cf9f-4879-b142-f50b0859f26f)

**Expected implementation （On Figma）**
![image](https://github.com/user-attachments/assets/1c6bd6c3-ab8a-4f21-8b7b-0cfc7a484309)

**Comment by c1c4da3300** [comment]
fixed
<img width="473" alt="image" src="https://github.com/user-attachments/assets/06cdfaf8-9201-4e46-aac2-6c7ece1aebf9">
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/77e0cbe1-b629-469a-bb68-6834d60c2416">
https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/commit/437a4eb6ce544ed0a7ec9ac0216c1fab32585fa5
