### ISSUE TITLE
[UI Issue] There is No Icon for "More" topic

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#65]
**Issue On:** Front End

**Describe the bug**
There is No Icon for "More" topic

**Current implementation**
![image](https://github.com/user-attachments/assets/574f2404-3903-4b4a-98d2-4ee36d2e1f41)

**Comment by c1c4da3300** [comment]
Fixed
More topic shouldn't be shown on the tag list, and now has been removed.
