### ISSUE TITLE
[UI Issue] Unable to click Topic button

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#66]
**Issue On:** Front End or Survey

**Describe the bug**
Unable to click Topic button, especially "More"

**Current implementation**
![image](https://github.com/user-attachments/assets/7363e84c-f37f-44b0-99f0-a08f817450b4)

**Comment by c1c4da3300** [comment]
Fixed: topic buttons now can be clicked and direct to topic page
<img width="497" alt="image" src="https://github.com/user-attachments/assets/78d69464-6bab-4a98-a1ed-2e933c69b633">

**Comment by c1c4da3300** [comment]
Fixed: topic buttons now can be clicked and direct to topic page
