### ISSUE TITLE
[UI Issue] the Navigation bar can be hide

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#67]
**Issue On:** Front End or Survey

**Describe the bug**
 The Page can be scroll down so that the Navigation bar will be hide

**Current implementation**
![image](https://github.com/user-attachments/assets/c00d7e98-4fd7-4ba6-87db-9ee2985656f8)

**Expected implementation （On Figma）**
Navigation bar should pined on top forever

**Comment by c1c4da3300** [comment]
fixed
![Image](https://github.com/user-attachments/assets/28f9aaf6-6adb-4c0c-974d-e3053ceff1fe)
![Image](https://github.com/user-attachments/assets/bf888862-67ea-48d1-a657-84f8d0306b8a)
https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/commit/437a4eb6ce544ed0a7ec9ac0216c1fab32585fa5
