### ISSUE TITLE
[UI Issue] Text in topic list item needs extra indentation

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#70]
**Issue On:** Front End

**Describe the bug**
Text in topic list item needs extra indentation

**Current implementation**
![image](https://github.com/user-attachments/assets/8ec31057-f8d7-40b2-91ab-7f2431247f65)

**Expected implementation （On Figma）**
![image](https://github.com/user-attachments/assets/d0c084be-fbb9-4c38-836b-ac5036a0ed03)

**Comment by c1c4da3300** [comment]
Fixed
https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/commit/902f381690c22324b0171577709dc14b308b2969
<img width="207" alt="image" src="https://github.com/user-attachments/assets/d0af8c83-6c7b-4597-a841-7931fcfd48f5">

**Comment by Xinlong-Wu** [comment]
no there need more indentation

**Comment by c1c4da3300** [comment]
Fixed
<img width="251" alt="image" src="https://github.com/user-attachments/assets/138aee96-7651-4857-9420-749cb228568a">

https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/commit/b591cbcae970f8cae48f9e7ed119e7238c3300f5
