### ISSUE TITLE
[UI Issue] Miss matched Design: Padding of navigation bar

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#72]
**Issue On:** Front End

**Describe the bug**
Padding of navigation bar are different between Prototype and Design

**Current implementation**
![image](https://github.com/user-attachments/assets/e05a1995-3ae3-441b-a99f-67c3b9b99b8a)

**Expected implementation （On Figma）**
![image](https://github.com/user-attachments/assets/0e948df9-3955-48fc-a705-954489071ae0)

**Comment by c1c4da3300** [comment]
fixed
<img width="971" alt="image" src="https://github.com/user-attachments/assets/3a889620-bbe7-4ba7-9861-04191c3d15c0">
https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/commit/2b554356c0c502cab88236d747a195e4f7914e5c
