### ISSUE TITLE
[UI Issue] Search  Text will start from left most border

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#73]
**Issue On:** Front End

**Describe the bug**
Search  Text will start from left most border

**Current implementation**
![image](https://github.com/user-attachments/assets/f2b75ed7-1432-4f7a-a5cd-a45b1c62a981)

**Expected implementation （On Figma）**
![image](https://github.com/user-attachments/assets/9b632fd6-45de-4a4b-bd27-1cef143001e3)

**Comment by c1c4da3300** [comment]
Fixed
https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/commit/902f381690c22324b0171577709dc14b308b2969
<img width="524" alt="image" src="https://github.com/user-attachments/assets/7a3c312e-90fe-4e53-b83c-904f6003e0cb">
