### ISSUE TITLE
[UI Issue] there is no gap between search Box and Poster

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#74]
**Issue On:** Front End or Survey

**Describe the bug**
there is no gap between search Box and Poster

**Current implementation**
![image](https://github.com/user-attachments/assets/134bc10d-4ea5-4c1f-8c56-ebbefcfe764e)

**Expected implementation （On Figma）**
![image](https://github.com/user-attachments/assets/3ef2ae94-0cbe-4ddd-9725-400a00f73860)

**Comment by c1c4da3300** [comment]
Fixed
https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/commit/902f381690c22324b0171577709dc14b308b2969
<img width="709" alt="image" src="https://github.com/user-attachments/assets/aa5edb6f-0db2-41b6-8031-a91f383a2ed4">
