### ISSUE TITLE
[UI Issue] Can't click Hot Posts Item

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#75]
**Issue On:** Front End

**Describe the bug**
Can't click Hot Posts Item

**Current implementation**
![image](https://github.com/user-attachments/assets/5d003d68-604c-4ed8-af8f-1346a2417417)

**Comment by c1c4da3300** [comment]
Fixed: now click on hot post will direct to search result
https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/commit/902f381690c22324b0171577709dc14b308b2969
