### ISSUE TITLE
[UI Issue] There is no search bar in topic page

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#77]
**Issue On:** Front End or Survey

**Describe the bug**
 There is no search bar in topic page

**Current implementation**
![image](https://github.com/user-attachments/assets/f452c0bd-f8a1-4d6d-9d01-2f4dc8222d06)

**Expected implementation （On Figma）**
![image](https://github.com/user-attachments/assets/66aeb975-e151-4929-b3a4-f68e6fb1bd2c)

**Comment by c1c4da3300** [comment]
fixed
<img width="888" alt="image" src="https://github.com/user-attachments/assets/18a94b03-a7fc-4694-8bd1-07e020e6eb2a">
https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/pull/41
