### ISSUE TITLE
[UI Issue] There is 3 row of Topic button

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#79]
**Issue On:** Front End 

**Describe the bug**
There is 3 row of Topic button on Apple XR

**Current implementation**
![image](https://github.com/user-attachments/assets/326f1226-69c3-48fb-8bad-c3caa663d11d)

**Comment by c1c4da3300** [comment]
fixed
<img width="326" alt="image" src="https://github.com/user-attachments/assets/22592633-59c8-46ff-bf61-401021a0a949">
