### ISSUE TITLE
[UI Issue] Miss matched Font family

### ISSUE THREAD

**Issue by Xinlong-Wu** [24-S1-2-C-Moral-Decisions/LandingSite#93]
**Issue On:** Front End

**Describe the bug**
Miss matched Font family

**Current implementation**
![image](https://github.com/user-attachments/assets/0dcafd2d-f3bb-4563-93f8-7eed0be47771)

**Expected implementation （On Figma）**
![image](https://github.com/user-attachments/assets/3303ac06-b046-40cc-99e9-22029d70a7d1)

**Comment by c1c4da3300** [comment]
fixed
<img width="135" alt="image" src="https://github.com/user-attachments/assets/a755b219-8f42-45df-a476-128a0498b1e7">
https://github.com/24-S1-2-C-Moral-Decisions/moral-front-end/commit/b591cbcae970f8cae48f9e7ed119e7238c3300f5
